### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' on a specific feed

### ISSUE THREAD

**Issue by pbrown280** [wking/rss2email#124]
Feed URL: http://feeds.megaphone.fm/WWO2453800973

Throws this exception since upgrade to v3.13:

2021-05-11 15:47:10,754 [INFO] refreshing feed savage (http://feeds.megaphone.fm/WWO2453800973 -> rss-savage@sfbrowns.com)
2021-05-11 15:47:10,754 [INFO] fetch savage (http://feeds.megaphone.fm/WWO2453800973 -> rss-savage@sfbrowns.com)
2021-05-11 15:47:11,366 [INFO] process savage (http://feeds.megaphone.fm/WWO2453800973 -> rss-savage@sfbrowns.com)
Traceback (most recent call last):
  File "/usr/local/bin/r2e", line 4, in <module>
    __import__('pkg_resources').run_script('rss2email==3.13', 'r2e')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/EGG-INFO/scripts/r2e", line 5, in <module>
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/rss2email/main.py", line 199, in run
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/rss2email/command.py", line 91, in run
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/rss2email/feed.py", line 933, in run
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/rss2email/feed.py", line 394, in _process
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/rss2email/feed.py", line 544, in _process_entry
  File "/usr/local/lib/python3.9/site-packages/rss2email-3.13-py3.9.egg/rss2email/feed.py", line 821, in _process_entry_content
  File "/usr/lib64/python3.9/xml/sax/saxutils.py", line 27, in escape
    data = data.replace("&", "&amp;")
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by pbrown280** [comment]
Verified that this feed works on rss2email v3.11 on Fedora 31.

Throws this exception on rss2email v3.13 on Fedora 34.

(Needed to upgrade to v3.13 to get rss2email to work on Fedora 34.)
